export type Section={title:string;text:string;items?:string[]};
export type Project={slug:string;number:string;title:string;subtitle:string;category:string;role:string;period:string;intro:string;image?:string;imageAlt?:string;sections:Section[];metrics?:{value:string;label:string}[]};
export const featuredProjects:Project[]=[
{slug:'terra',number:'01',title:'從零建立一間公司',subtitle:'人力資源管理 × Terra',category:'HR / Recruiting / Business Simulation',role:'Recruitment Specialist｜招募專員',period:'大二 · 人力資源管理',intro:'在一學期的模擬企業實作中，理解營運、組織與人才如何彼此連動。這也是我開始對 HR 產生明確興趣的課程。',sections:[{title:'一學期的模擬企業',text:'在夏侯欣鵬教授的課程中，學生從公司名稱、產品與服務、商業模式，到組織架構、部門、人力需求、財務與營運，從零建立 Terra。老師每週要求報告並檢核方向，期末有校園園遊會型態的販售情境。Terra 是學生模擬企業。'},{title:'我的角色：讓招募有依據',text:'HR Team 由 1 位主管、2 位招募專員與 2 位甄試專員組成。我與 HR Team 建立組織架構，負責招募相關工作。',items:['撰寫全部職位 JD','建立履歷書審標準，應用信度與效度概念','接收與篩選履歷','規劃招募流程、面試時程與通知']},{title:'分工與團隊成果',text:'我會參與商業模式、財務與業務討論，但不是這些功能的主責。績效評估也不是我的主責；實際販售由業務人員執行。'},{title:'理解公司，才知道要找什麼人',text:'最重要的收穫，是第一次全方面看見公司如何建立與運作。HR 並非孤立的功能：組織架構、職位與人力需求，都必須回到企業要做什麼，也需要跨部門與跨角色的溝通。'}],metrics:[{value:'91',label:'課程成績'},{value:'1',label:'學期模擬企業實作'}]},
{slug:'smart-retail',number:'02',title:'走出資訊迷宮',subtitle:'產業管理研討 × 智慧零售',category:'Industry Research / Digitalization',role:'產業研究與課程實作',period:'大三 · 產業管理研討',intro:'把便利商店第一線的觀察帶進研究，學習先界定產業，再從大量資訊中整理出有依據的結論。',sections:[{title:'從門市經驗出發',text:'FamilyMart 的工作讓我接觸訂購、庫存、顧客服務與門市流程。智慧零售研究讓這些日常經驗成為理解數據、流程與商業模式的素材。無人商店尤其啟發我對 AI、數位化與人的工作如何改變的興趣。'},{title:'先定義研究的是什麼',text:'楊君琦、林瑩滋教授的課程，以及黃博士的分享，幫助我建立研究方法感。先理解產業遊戲規則與 Players；分清「智慧零售化」與「零售智慧化」；在搜尋前定義研究範圍，避免資料越找越散。'},{title:'我的研究範圍',text:'主要負責產業定義、便利商店供應鏈、智慧零售趨勢與應用、市場／Players／資料整理及未來展望。從第一線經驗出發，學習區分產業研究與公司分析。'},{title:'學習並實作研究框架',text:'課程接觸產業定義、供應鏈、市場規模、PEST、Five Forces、SCP 與 Business Model，也第一次認真檢視永續報告書。這些是基本方法的學習與實作；當時對 SWOT / STP 仍不熟悉。'},{title:'資料很多，仍然需要結論',text:'當時什麼都想放，也容易混淆公司分析與產業分析。在有限時間內整理並報告，讓我意識到研究需要篩選、界定、架構與結論，而非持續堆疊資料。'}]},
{slug:'bamboo-tea',number:'03',title:'讓茶的價值被看見',subtitle:'竹峰茗茶 × 第三屆社企永續聚落',category:'Sustainability / Social Enterprise / Collaboration',role:'專案規劃、內容執行與現場推廣',period:'大三 · 組織學習與社會探究',intro:'從茶園走進永續聚落，透過實地了解、內容與現場互動，讓更多人理解茶背後的資源、文化與人。',image:'images/bamboo-tea.webp',imageAlt:'第三屆社企永續聚落竹峰茗茶團隊合照',sections:[{title:'從課堂走到真實場域',text:'在李禮孟教授的課程中，團隊從社企永續聚落合作名單選擇竹峰茗茶，合作企業主也是輔大企管博士班學長。工作涵蓋茶園參訪、訪談與拍攝規劃、行程交通、影片與海報，以及展售與現場銷售。'},{title:'我的貢獻',text:'Participated in interview planning and field content production。',items:['專案行程與交通安排','訪談安排與拍攝規劃','團隊協作與資訊整理','內容執行、現場推廣及活動當天工作']},{title:'永續不只是一個分類',text:'Resource Value：看見外觀不完美、仍有價值的次級茶。Cultural Continuity：茶承載在地文化、農業、人情與傳承。Community Connection：透過故事、互動與介紹，讓參與者理解品牌理念。'},{title:'讓不同專長發揮',text:'企管、法律意識、內容傳播與專案管理，提供不同理解永續的角度。我仍然喜歡領導與主動推進事情，也能成為可靠的組員，把擅長的工作做好，讓不同人的專長被發揮。'}],metrics:[{value:'≈ NT$3,100',label:'Team Project Outcome · 原始目標'},{value:'≈ NT$6,000',label:'Team Project Outcome · 團隊營業額'},{value:'Sold out',label:'Team Project Outcome · 冷泡茶售罄'}]},
{slug:'sel',number:'04',title:'把理解，變成可以學習的內容',subtitle:'SEL Learning Design',category:'Learning & Development / Education',role:'教材主導製作與教育訓練執行',period:'114–115 學年度 · SEL 教材製作',intro:'參與 114–115 學年度的 SEL 教材簡報與培訓內容製作，把對人的理解轉化為教學內容、培訓簡報與影片。',sections:[{title:'Learning & Development 的起點',text:'這份經驗不只是偏鄉服務的一部分，也是我對未來 L&D 發展很有成就感的啟蒙。從內容準備到教育訓練執行，讓我實際練習如何支持他人的學習。'},{title:'我的工作',text:'製作 SEL 教材簡報與 4 支培訓影片，協調 1 場 SEL 月講座。',items:['SEL 教材與教學內容設計','Training Deck 與簡報設計','教學影片錄製／製作','教育訓練執行']},{title:'內容與現場相互支持',text:'帶班經驗中的學伴支持、師長溝通與需求回應，讓我更注意學習者的處境。把教材、訓練與帶班支持串接，讓內容回應真實學習需求。'}],metrics:[{value:'4',label:'培訓影片'},{value:'1',label:'SEL 月講座協調'}]}
];

