import {projects} from './v1';
import {featuredProjects} from './featuredProjects';
import timeline from './timeline-data.json';
export const nav=[["home", "ABOUT ME", "個人簡介"], ["experience", "EXPERIENCE", "工作經歷"], ["competitions", "AWARDS & ACHIEVEMENTS", "競賽榮耀"], ["capstone", "RESEARCH & PROJECTS", "研究實作"], ["academic", "ACADEMIC PERFORMANCE", "學業表現"], ["leadership", "EXTRACURRICULAR ACTIVITIES", "課外活動"], ["honors", "CREDENTIALS", "相關證明"], ["contact", "CONTACT ME", "聯絡方式"]];
export const contacts=[{label:'Email',url:'mailto:aa411382423@gmail.com'},{label:'LinkedIn',url:'https://www.linkedin.com/in/annalearner/'},{label:'GitHub',url:'https://github.com/aa2423-bit'},{label:'PDF Resume',url:'/resume/Anna_Peng_Resume.pdf'}];
export const bio=["Hello, I’m Anna 淑萍！", "我的個性外向親和、主動積極，也重視責任與細節，喜歡與人互動、理解需求，並把事情有條理地完成。目前就讀輔仁大學企業管理學系，輔修財經法律系並修習企業財稅學分學程，具備人資營運、招募、教育訓練、活動籌備與專案協作等實務經驗。", "同時為 HRFriday 第五屆高潛學員，透過一年期培育與專案實作，建立人力資源選、育、用、留與勞動法規基礎，並接觸數位招募及雇主品牌社群經營。執行任務時，我重視資訊正確性、流程完整性與效率，習慣先釐清目的與現況，再整合資訊、規劃執行，並從過程中找出問題與改善空間。", "我具備 **Microsoft 365、Google Workspace、生成式 AI 工具（ChatGPT、Gemini、NotebookLM、Perplexity）** 的應用能力，以及 **RPA 自動化基礎概念**，並能運用 **Canva、CapCut** 進行基礎圖文設計與影音剪輯。我持續探索數位工具在降低重複性作業、提升效率與優化流程上的應用，並運用規劃執行、資訊整合與問題解決能力，產出穩定、有效率且具品質的工作成果。"];
export const jobs=[{"slug": "hota", "company": "和運租車", "role": "管理部人力資產室實習生", "date": "Jun 2026 - Present", "image": "hota", "points": ["新南向外籍技術實習生招募：擔任 4 所大專校院合作窗口，完成外籍生任用調研、合作提案與簽呈", "識別證製卡流程優化提案：完成 3 家廠商比價，優化後五年節省約5萬元、製卡時程由 2–3 週縮短至 1 天", "經營雇主品牌社群：擔任 LinkedIn 管理員，完成 2 篇 FB 貼文及HAP開箱影片社群影音製作", "執行 HRM 人事作業：負責系統建檔、報到資料管理儀表板與服務證明製作與各單位考勤盤點及異常追蹤"]}, {"slug": "hrfriday", "company": "HRFriday 人資小週末", "role": "高潛力學生團｜第五屆", "date": "Aug 2025 - Aug 2026", "image": "hrfriday", "points": ["第六屆高潛學員招募專案副召，參與招募規劃、履歷書審、面試協調與跨組執行，順利招募 12 位高潛夥伴。", "第七屆高潛學員招募副面試官，參與甄試、口試與候選人評估，累積從應徵、招募執行到面試評估的完整招募歷程。"]}, {"slug": "familymart", "company": "全家便利商店", "role": "高階服務人員", "date": "Apr 2023 - Jul 2026", "image": "", "points": ["執行商品訂購、到貨驗收與上架陳列，透過定期盤點與效期管理，維持門市庫存帳實一致", "維護賣場環境整潔與標準化營運品質，落實門市服務規範與日常作業流程", "負責顧客服務與團購社群經營，管理約 200 人社群並協助推動選品銷售", "核對日營收金額、帳務傳輸，完成每日結報並維持帳務核對正確"]}, {"slug": "community", "company": "輔仁大學台灣偏鄉教育關懷中心", "role": "帶班約聘助理", "date": "Feb 2023 - Jun 2026", "image": "community", "points": ["管理值班現場異常處理，穩定媒合每梯次約 60 組大學伴在線教學順利運行", "執行校園跑班招募事務，單學期跑班招募逾 100 名大學生，完成約 70% 學伴人力需求", "擔任技術教育訓練講師，引導約 60–70 位大學生掌握系統操作，建立課程標準化操作流程", "製作標準培訓教材（含簡報與影片），獨立產出 2 支教學影片，提升培訓內容一致性", "管控學伴出缺席狀況並即時補位，確保陪伴品質並控制臨時缺課率維持於 3% 以下", "維繫學習端師長聯繫窗口，建立完整異常處理追蹤機制，提升問題回報與溝通效率", "完成 SEL 專案簡報製作及拍攝 2 支培訓影片，負責 SEL 月培訓講座接洽與執行"]}, {"slug": "recruitment", "company": "亞瑞特數位社群行銷有限公司", "role": "人事招募工讀", "date": "Jul 2025 - Aug 2025", "image": "", "points": ["執行 104 平台人才搜尋與初步篩選，日均處理 30–50 份履歷，提升招募效率並補實 1 項職缺需求。", "負責電話開發與候選人初步聯繫，透過有效溝通維持穩定的面談轉換率 75%。", "負責面試流程與時程安排，每週平均排定 5 場面試。"]}, {"slug": "caves", "company": "敦煌書局股份有限公司輔仁大學門市部", "role": "門市工讀", "date": "Sep 2023 - Dec 2024", "image": "", "points": ["維護校園門市書籍上架、陳列整理與庫存盤點", "整理架上圖書與展示書區", "負責開學季尖峰時段收銀結帳與顧客諮詢"]}];
export const awards=[{slug:'future2035',title:'2035 青年人生活情境競賽',award:'銀質獎 / 第二名',role:'組長｜主題發想、競賽窗口、主要發表',text:'以「聽見『心』未來」整合心理與企管觀點，從員工狀態、隱私、EAP 與可行性思考未來方案。'},{slug:'japan',title:'2024 跨域學習成果競賽',award:'第一名',role:'組長',text:'參與跨領域學習成果競賽，運用 Gemini Data 圖數據工具，完成日本旅遊與住宿資料整理、分析與成果發表。'}];
export const courses=[{slug:'terra',title:'人力資源管理｜Terra 模擬企業',category:'HR / BUSINESS SIMULATION',text:'從組織與職位需求出發，建立課堂模擬企業的招募流程。',tags:['JD','招募流程','課程成績 91']},{slug:'smart-retail',title:'產業管理研討｜智慧零售',category:'INDUSTRY RESEARCH',text:'把第一線門市經驗帶進產業研究，練習界定問題與整理洞察。',tags:['供應鏈','Players','數位化']},{slug:'bamboo-tea',title:'組織學習與社會探究｜竹峰茗茶 × 第三屆社企永續聚落',category:'SUSTAINABILITY / COLLABORATION',text:'從茶園訪談到永續聚落，參與真實外部合作與現場推廣。',tags:['外部合作','社企永續','內容製作']}];
export const activities=[{slug:'residence',title:'宜真宜善學苑｜苑代表',role:'苑代表',date:'Jul 2024 - Jun 2025',text:'服務 500+ 位住民，協調 8 位樓層幹部，統籌 18 項活動、年度預算與住民溝通。',path:'/leadership/residence'},{slug:'camps2026',title:'2026《伴您好讀》聯合相見歡',role:'國小組活動組總負責人',date:'2026',text:'約 35 位學童、四天三夜。負責活動企劃、時間、餐食、主持、協調與現場處理。',path:'/activities/camps2026'},{slug:'camps2024',title:'2024 台東莿桐夏日學堂',role:'隊長',date:'Jul 22 - Jul 26, 2024',text:'一週課程設計、活動細流與團隊協調，並在颱風影響下調整原有安排。',path:'/activities/camps2024'}];
export const more=[['happ','人力規劃與選才｜Happ. 小樹屋'],['railway','組織與社會發展｜台鐵公司化'],['curation','策展概念與實作｜酒酒不能自己'],['psychology','工商心理學'],['finance','國際財務管理｜台積電赴美設廠'],['labor','勞資關係與薪酬管理']];
export type StorySection={title:string;text:string;items?:string[]};
export type Story={slug:string;path:string;title:string;category:string;role:string;date:string;background:string;image?:string;metrics:string[];sections:StorySection[];resources:string[];gallery?:string[]};
export const stories:Story[]=projects.map(p=>{const original=featuredProjects.find(x=>x.slug===p.slug);return {slug:p.slug,path:'/projects/'+p.slug,title:p.title,category:p.category,role:p.role,date:original?.period||(p.slug==='capstone'?'Feb 2025 - Dec 2025':'第五屆學習／第六屆招募'),background:original?.intro||p.context,image:p.slug==='sel'?undefined:p.slug,metrics:original?.metrics?.map(m=>m.value+'｜'+m.label)||[p.outcome],sections:original?.sections||p.sections||[],resources:[p.slug]};});
const hr=stories.find(s=>s.slug==='hrfriday')!;hr.role=jobs[1].role;
hr.sections.push({title:'上半年學習',text:'接觸招募甄選與 JD、訓練發展、薪酬福利、員工關係與勞動法規，整理實務觀點。學習足跡見上半年簡報。'},{title:'下半年學習',text:'持續把人資學習連結到招募流程與團隊執行，相關紀錄保留於下半年學習簡報。'},{title:'科技人資 / AI × HR',text:'關注人資與 AI 數位平台、人資數據庫、人資 AI Agent、AI 時代的人才與組織轉型，以及多模態 AI 與人才管理。'},{title:'我的反思',text:'從候選人轉為招募流程設計與執行者，開始理解候選人體驗、評估一致性與跨組協作如何共同影響一場招募。'});
stories.find(s=>s.slug==='smart-retail')!.sections.push({title:'個人分工',text:'Anna 負責 P1–P18；P19–P35 主要由另一位組員負責。'});
const cap=stories.find(s=>s.slug==='capstone')!;cap.gallery=['framework'];cap.sections.push({title:'研究架構',text:'研究聚焦 AI 焦慮、AI 接受、工作生活平衡與工作績效。架構圖中的箭頭代表研究假設；本頁不推定未確認的研究結論。'},{title:'團隊研究規模',text:'347 份有效問卷與 10 位跨產業決策主管及人資專業人士訪談，為團隊研究規模。我的參與為文獻整理、研究架構、問題聚焦與概念整合。'});
stories.push(
 {slug:'hota',path:'/experience/hota',title:'和運租車｜人力資源實習',category:'WORK EXPERIENCE',role:jobs[0].role,date:jobs[0].date,image:'hota',background:'在實習中參與人才專案、流程研究與人資日常營運支援。',metrics:[],sections:[{title:'我的角色與工作範圍',text:'支援新南向人才專案、校方合作研究、提案與內部流程整理。',items:jobs[0].points},{title:'方法與協作',text:'識別證流程與廠商方案比較；雇主品牌及社群內容支援；人資營運與新進流程支援。'},{title:'成果與我的感觸',text:'實習持續進行中。具體成果數據、可公開作品與個人反思尚未提供。'}],resources:['hota']},
 {slug:'community',path:'/experience/community',title:'輔仁大學台灣偏鄉教育關懷中心',category:'WORK EXPERIENCE',role:jobs[1].role,date:jobs[1].date,image:'community-team',background:'從招募引才、入職培訓、學習設計、雇主品牌，到 Program Operations，支持大學生投入偏鄉教育。',metrics:['100+｜單學期招募','4 次｜教育訓練講師','35 位｜營隊學童','約 60 組｜每梯次大小學伴'],sections:[{title:'Key Responsibilities & Contributions',text:'工作串接招募、訓練、內容傳遞與日常營運，兼顧學伴、師長及大學團隊的需求。'},{title:'招募引才｜Talent Attraction',text:'執行校園跑班與到班宣傳，介紹單位、服務內容與參與方式，進行招募前端溝通。單學期招募逾 100 位大學生，約完成 70% 學伴人力需求。'},{title:'入職培訓｜Onboarding & Training',text:'113–115 學年度共擔任 4 次講師，製作教育訓練簡報、影片，擔任單位介紹主持人，說明新人／學伴系統操作與流程。'},{title:'學習設計｜SEL',text:'完成 114–115 學年度 SEL 教材簡報，拍攝／製作 4 支培訓影片，接洽並執行 1 場 SEL 月培訓講座。從內容設計到傳遞，練習將抽象概念轉化為清楚、可理解的內容。'},{title:'雇主品牌｜Employer Branding',text:'114-1 核心幹部期初培訓擔任攝影師暨影片剪輯，記錄團隊服務現場與培訓內容，將組織文化與教育理念轉化為對外溝通的影像。'},{title:'Program Operations',text:'維持每梯次約 60 組大小學伴連線教學，管理出缺席、即時補位與師長聯繫。於 2026《伴您好讀》擔任國小組活動組總負責人，服務約 35 位學童，規劃四天三夜活動、交通教育、餐食與主持，協調現場狀況。'},{title:'我的感觸與學習',text:'這段經驗讓我更加確立對 Learning & Development 的興趣，也理解組織形象來自成員真實參與的故事。把招募、教材、訓練與帶班支持連起來，才能讓內容回應現場需求。'}],resources:['community','sel','training114','camps2026'],gallery:['community-training']},
 ...awards.map(a=>({slug:a.slug,path:'/awards/'+a.slug,title:a.slug==='future2035'?'聽見「心」未來｜2035 青年人生活情境競賽':a.title,category:'SELECTED AWARDS',role:a.role,date:a.slug==='japan'?'2024':'2035 青年人生活情境競賽',image:a.slug,background:a.text,metrics:[a.award],sections:a.slug==='future2035'?[{title:'背景與我的角色',text:'與兩位馬來西亞心理系同學合作，整合人資與投資領域教授的建議，提出關注員工狀態、預防安靜離職並連結 EAP 的構想。我負責規則盤點、對外窗口、組內分工與主要發表。'},{title:'核心方法論與解方亮點',text:'以員工狀態與心理支持為起點，整合心理與企管觀點，將問題轉化為可以溝通的未來生活情境提案。'},{title:'Privacy / EAP / 可行性',text:'團隊從隱私、資料儲存、風險控管與可行性檢視方案，思考心理支持與 EAP 的連結。此為競賽提案，並非已上線服務。'},{title:'團隊合作',text:'身為組長，協調不同專業背景的觀點、分工與時程，擔任競賽窗口及主要發表者；得獎為團隊成果。'},{title:'我的反思',text:'跨域整合、領導與表達之外，也需要能回答方案如何落地，並回應隱私與風險的提問。'}]:[{title:'背景與我的角色',text:'以疫情後日本旅遊與住宿為研究主題，擔任組長，進行資料蒐集、清理與整理，完成成果整合及發表。'},{title:'核心方法',text:'Data → Cleaning → Visualization → Insight → Action',items:['資料蒐集：日本旅遊與住宿資料','Cleaning：清理及整理資料','Visualization：使用 Gemini Data 操作與呈現','Insight：解讀資料與整合成果','Action：完成研究發表']},{title:'我的學習',text:'從資料清理，到工具操作、解讀與發表，練習把零散資料整理成能與團隊溝通的研究成果。'}],resources:[a.slug],gallery:a.slug==='future2035'?['award-certificate']:[]})),
 {slug:'residence',path:'/leadership/residence',title:activities[0].title,category:'LEADERSHIP & OPERATIONS',role:'苑代表',date:activities[0].date,image:'residence',background:'一整年的領導，不只在活動當天。從年度預算、幹部分工，到日常住民需求，持續協調人、資源與現場。',metrics:['500+｜住民','8 位｜樓層幹部','18 項｜年度活動','1 學年｜預算與營運'],sections:[{title:'我的角色與年度預算',text:'統籌活動與日常營運、幹部分工、進度與現場支援。作為住民、樓層幹部與管理員之間的窗口，規劃年度活動預算、資源配置與支出追蹤，協調採購、經費及核銷。'},{title:'六大精選專案',text:'從新生入住到年度成果回報，六個專案呈現不同的協調與執行場景。',items:[timeline[3],timeline[4],timeline[8],timeline[11],timeline[12],timeline[17]].map(t=>t.title+'：'+t.text)},{title:"SuSuSu Super X'mas",text:'擔任副召集人。活動整體規模：約 14 萬元總經費、約 60 位工作人員、約 200 位住民。協作活動企劃、流程、預算及資金管理、現場執行與跨文化交流。'},{title:'我的反思',text:'領導不只在活動當天，也包含整年的預算、分工與日常需求回應。這段經驗讓我持續練習協調人、資源與現場，並將年度經驗交接給下一屆。'}],resources:['leadership'],gallery:['residence-group','residence-exchange']},
 ...activities.slice(1).map(a=>({slug:a.slug,path:a.path,title:a.title,category:'EXTRACURRICULAR ACTIVITIES',role:a.role,date:a.date,image:a.slug,background:a.text,metrics:a.slug==='camps2026'?['約 35 位｜學童','四天三夜｜活動']:['一週｜課程設計'],sections:a.slug==='camps2026'?[{title:'我的角色',text:'國小組活動組總負責人，面對小一至小六、約 35 位學童，主導專案與活動設計。'},{title:'企劃與現場執行',text:'規劃台北捷運體驗與交通教育、城市實境桌遊及團隊闖關，控管時間與進度，安排午餐訂購與發放並主持活動。'},{title:'協調與現場處理',text:'協調老師、學生與大學生夥伴，回應現場臨時狀況，兼顧活動安全與參與品質。'},{title:'我的反思',text:'這段經驗讓我練習同時照顧參與者需求、現場節奏與團隊協作，在時間限制與突發狀況中調整安排。'}]:[{title:'我的角色',text:'擔任隊長，協調一週課程設計、活動細流、流程表、進度、彩排與團隊分工。'},{title:'颱風應變',text:'颱風打亂原有安排，團隊重新調整規劃內容與現場節奏。'},{title:'我的反思',text:'這段經驗讓我練習調整專案、穩住節奏與凝聚團隊，累積臨場應變與團隊合作經驗。'}],resources:[a.slug]}))
);


// V3.1 specification overrides earlier narrative facts.
for(const story of stories){const job=jobs.find(j=>j.slug===story.slug);if(job){story.role=job.role;story.date=job.date;}}
const h31=stories.find(s=>s.slug==='hota')!;
h31.background='在人力資產室的實習，涵蓋外籍人才合作、識別證流程優化、雇主品牌與人事營運。';
h31.sections=[{title:'從人才調研到校園合作',text:jobs[0].points[0]+'。'},{title:'把流程改善落實到方案',text:jobs[0].points[1]+'。'},{title:'雇主品牌與人事營運',text:jobs[0].points.slice(2).join('。')+'。'}];
const c31=stories.find(s=>s.slug==='community')!;
c31.metrics=['100+｜單學期招募','約 70%｜人力需求','約 60 組｜每梯次教學','3% 以下｜臨時缺課率'];
c31.sections=[{title:'讓教學現場穩定運作',text:jobs[3].points[0]+'。'+jobs[3].points[4]+'。'},{title:'從校園招募到技術培訓',text:jobs[3].points[1]+'。'+jobs[3].points[2]+'。'},{title:'教材、SEL 與溝通追蹤',text:jobs[3].points[3]+'。'+jobs[3].points[5]+'。'+jobs[3].points[6]+'。'},{title:'我的反思與學習',text:'這段經驗讓我更加確立對 Learning & Development 的興趣，也理解組織形象來自成員真實參與的故事。把招募、教材、訓練與帶班支持連起來，才能讓內容回應現場需求。'}];
hr.sections.unshift({title:'招募實務：第六屆招募與第七屆面試',text:jobs[1].points.join(' ')});
const sel31=stories.find(s=>s.slug==='sel')!;
sel31.sections=sel31.sections.map(s=>({...s,text:s.text.replace('4 支培訓影片','2 支 SEL 培訓影片')}));
sel31.metrics=['2 支｜SEL 培訓影片'];

import finalCopy from "./final-copy.json";
for(const story of stories){const copy=finalCopy[story.slug as keyof typeof finalCopy];if(copy){story.sections=copy;story.background="";story.metrics=[];}}
Object.assign(stories.find(s=>s.slug==="hota")!,{"title": "和運租車｜管理部人力資產室實習生"});
Object.assign(stories.find(s=>s.slug==="community")!,{"title": "輔仁大學台灣偏鄉教育關懷中心｜Program Assistant", "role": "從招募、培訓到營運，支持一套陪伴系統真正運作"});
Object.assign(stories.find(s=>s.slug==="future2035")!,{"title": "聽見「心」未來｜2035 青年人生活情境競賽", "category": "智慧永續全國競賽｜銀質獎・第二名", "role": "組長｜提案發想・方案規劃・內容整合・主要發表", "date": "2024.09–2024.12｜心理系 × 企管系跨域團隊"});
Object.assign(stories.find(s=>s.slug==="japan")!,{"title": "2024 跨域學習成果競賽｜日本旅遊與住宿資料分析", "role": "第一名｜組長｜資料蒐集、清理、Gemini Data 分析與成果發表"});
Object.assign(stories.find(s=>s.slug==="terra")!,{"title": "人力資源管理｜Terra 模擬企業", "role": "課程成績 91 分｜一學期模擬企業實作"});
Object.assign(stories.find(s=>s.slug==="smart-retail")!,{"title": "產業管理專題｜智慧零售研究", "role": "從便利商店第一線經驗出發，學習如何界定產業、建立研究框架，並把大量資訊整理成有依據的結論。"});
Object.assign(stories.find(s=>s.slug==="bamboo-tea")!,{"title": "社會企業與永續實作｜竹峰茗茶合作專案", "role": "從茶園走進永續聚落，也讓我第一次真正思考：永續究竟代表什麼？"});
Object.assign(stories.find(s=>s.slug==="residence")!,{"date": "2024.07–2025.06｜一學年的宿舍領導與營運", "background": "擔任苑代表期間，我與 **8 位樓層幹部**共同支持 **500+ 位住民**的住宿生活，一學年間參與與推進 **18 項活動及營運任務**。\n\n我的工作橫跨年度活動規劃、預算與資源配置、幹部分工、住民溝通及現場異常處理，也作為**住民、樓層幹部與宿舍管理員之間的協調窗口**。這段經驗讓我第一次長時間承擔一個組織的日常運作，而不只是完成單次活動。"});
Object.assign(stories.find(s=>s.slug==="camps2026")!,{"title": "2026《伴您好讀》聯合相見歡｜國小組活動組總負責人", "role": "4 天 3 夜｜約 35 位學童｜小一至小六｜活動企劃與現場統籌"});
Object.assign(stories.find(s=>s.slug==="camps2024")!,{"title": "2024 台東莿桐夏日學堂｜隊長", "role": "1 週｜課程設計｜團隊協調｜颱風應變"});
Object.assign(stories.find(s=>s.slug==="hrfriday")!,{"category": "EXTRACURRICULAR ACTIVITIES"});
activities.push({slug:'hrfriday',title:'HRFriday / 人資小週末',role:'高潛學員・招募專案副召・副面試官',date:'2025–2026',text:'累計完成 5 項、129 小時培訓，從 HR 基礎學習走進招募實作。',path:'/projects/hrfriday'});
for(const c of courses){c.title=stories.find(s=>s.slug===c.slug)!.title;}

stories.find(s=>s.slug==='hrfriday')!.title="人資小週末 HRFriday｜第五屆高潛力學生團學員";
stories.find(s=>s.slug==='hrfriday')!.category="WORK EXPERIENCE";
