import {useEffect} from 'react';
import {Link,Route,Routes,useLocation} from 'react-router-dom';
import {ArrowUpRight} from 'lucide-react';
import {asset,forProject} from './content/resources';
import {nav,contacts,bio,jobs,awards,courses,activities,more,stories} from './content/v3';
import imageMap from './content/image-map-v3.json';
import {Carousel,Rail,Evidence,published,type Slide} from './Media31';
const gallery=(section:string)=>published.filter(p=>(p as Slide & {section:string}).section===section);
function Photo({name,hero=false}:{name:string;hero?:boolean}){const p=imageMap[name as keyof typeof imageMap];return p&&published.some(x=>x.url===p.asset)?<img src={asset(p.asset)} alt={name==='hrfriday'?'HRFriday 人資小週末':name==='hota'?'和運租車':name==='community'?'偏鄉教育關懷中心':'專案影像'} width={p.dimensions[0]} height={p.dimensions[1]} loading={hero?'eager':'lazy'} fetchPriority={hero?'high':'auto'} style={{objectFit:'contain',objectPosition:p.position,aspectRatio:p.crop}}/>:null;}
function Contacts({download=false}:{download?:boolean}){return <div className="v3-contacts">{contacts.filter(c=>download||c.label!=='Email').map(c=><a key={c.label} href={c.url.startsWith('/')?asset(c.url):c.url} {...(c.label==='Email'?{}:{target:'_blank',rel:'noopener noreferrer'})}>{c.label==='PDF Resume'?'Resume':c.label}<ArrowUpRight size={15}/></a>)}</div>}
function Resources({slugs,children}:{slugs:string[];children?:React.ReactNode}){const resources=slugs.flatMap(forProject).filter(r=>r.external||published.some(p=>p.url===r.url));return resources.length?<div className="resource-links">{resources.map(r=><a key={r.id} href={r.external?r.url:asset(r.url)} target="_blank" rel="noopener noreferrer">{r.label}<b aria-hidden="true">↗</b></a>)}{children}</div>:null}
function Header(){return <header className="v3-header"><div className="v3-header-top"><Link className="v3-brand" to="/#home">找到自己真正喜歡的事，並讓喜歡的事變得有價值</Link></div><nav className="v3-desktop-nav" aria-label="主要導覽">{nav.map(([id,en,zh])=><Link key={id} to={'/#'+id}><span>{zh}</span></Link>)}</nav></header>}
function Back(){return <button className="cta31" onClick={()=>window.history.back()}>← 回上一頁</button>}
function Copy({text}:{text:string}){return <>{text.split(/\n\s*\n/).map((p,i)=><p key={i}>{p.split(/(\*\*.*?\*\*)/g).map((v,j)=>v.startsWith('**')?<strong key={j}>{v.slice(2,-2)}</strong>:v)}</p>)}</>}
function Cta({to,children}:{to:string;children:React.ReactNode}){return <Link className="cta31" to={to}>{children}<b aria-hidden="true">→</b></Link>}
function Contact(){return <section id="contact" className="v3-contact"><h2>CONTACT ME｜與我聯繫</h2><p>Thank you for taking the time to review my portfolio. Btw, I look forward to connecting with you.</p><Contacts download/></section>}
const averages=[85.50,83.50,83.15,89.72,86.92,88.61,86.92,93.09],credits=[20,22,26,29,26,33,12,11],semesters=['大一上','大一下','大二上','大二下','大三上','大三下','大四上','大四下'];
function Academic(){return <section id="academic"><h2>ACADEMIC PERFORMANCE｜學業表現</h2><div className="split31"><div><div className="academic-stats"><p><strong>3.76</strong>累計 GPA</p><p><strong>86.92</strong>四年平均成績</p><p><strong>14.71%</strong>甄試名次百分比</p></div><Copy text={"大學四年間累計修習 **179 學分**，在跨領域修課與實務活動並行的情況下，仍維持 **累計 GPA 3.76、四年平均成績 86.92 分**。隨著學習方法與時間管理逐漸成熟，後期學業表現持續提升，並於大四下取得 **93.09 分**的學期平均成績，展現穩定投入與持續精進的學習態度。"}/></div><div><svg className="chart31" viewBox="0 0 560 230" role="img" aria-label="八學期平均成績趨勢，83.15 至 93.09"><line x1="25" x2="530" y1="180" y2="180" stroke="#d7cfc2"/><polyline fill="none" stroke="#8e4936" strokeWidth="3" points={averages.map((v,i)=>`${35+i*69},${180-(v-80)*10}`).join(' ')}/>{averages.map((v,i)=><g key={i}><circle cx={35+i*69} cy={180-(v-80)*10} r="5" fill="#8e4936"/><text x={35+i*69} y={165-(v-80)*10} textAnchor="middle">{v.toFixed(2)}</text><text x={35+i*69} y="211" textAnchor="middle">{semesters[i]}</text></g>)}</svg><details><summary>查看各學期成績與學分</summary><table><thead><tr><th>學期</th><th>平均</th><th>學分</th></tr></thead><tbody>{averages.map((v,i)=><tr key={i}><td>{semesters[i]}</td><td>{v.toFixed(2)}</td><td>{credits[i]}</td></tr>)}</tbody></table></details></div></div><div id="learning"><h3>其他修習課程與成果</h3><Rail label="更多課程">{more.map(([slug,title])=><article key={slug}><Link className="course-cover" to={'/learning/more#'+slug}><img src={slug==='finance'?'https://i.ytimg.com/vi/jYj7EphpX08/hqdefault.jpg':asset('media/course-covers/'+slug+'.jpg')} alt={title+'｜成果封面'} loading="lazy"/></Link><p className="eyebrow">COURSEWORK</p><h3 title={title}>{title}</h3><Cta to={'/learning/more#'+slug}>查看更多</Cta></article>)}</Rail></div></section>}
function Home(){return <div className="v3-home wrap">
<section id="home" aria-label="ABOUT ME｜關於我"><div className="v3-summary"><div><h1>{bio[0]}</h1><p className="hero-info">輔仁大學｜企業管理學系 X 輔修財經法律系 X 企業財稅學分學程</p><p>Expected Graduation｜Dec 2026</p><Contacts/>{bio.slice(1).map(p=><p key={p}>{p}</p>)}<div className="v3-tags">{['外向親和','主動學習','多元探索','整合思維','規劃執行','跨領域學習'].map(t=><span key={t}>{t}</span>)}</div></div><div className="v3-portrait"><Carousel items={gallery('hero')} label="Anna 形象照" hero/><p className="portrait-email">aa411382423@gmail.com</p></div></div></section>
<section id="experience"><h2>EXPERIENCE｜工作經歷</h2>{jobs.map(j=><article className={'v3-job'+(j.slug==='hrfriday'?' hr-featured':'')} key={j.slug}><div>{j.image&&<div className={'v3-logo logo-'+j.slug}><Photo name={j.image}/></div>}<h3>{j.slug==='hrfriday'?'人資小週末 HRFriday':j.company}</h3><p className="role">{j.slug==='hrfriday'?'第五屆高潛力學生團學員':j.role}</p><p className="v3-date">{j.date}</p></div><div><ul>{j.points.map(p=><li key={p}>{p}</li>)}</ul>{j.slug==='hrfriday'&&<Resources slugs={['hrfriday']}><Cta to="/projects/hrfriday">查看更多</Cta></Resources>}<div>{!['recruitment','caves','hrfriday'].includes(j.slug)&&<Cta to={j.slug==='hrfriday'?'/projects/hrfriday':'/experience/'+j.slug}>查看更多</Cta>}</div></div></article>)}</section>
<section id="competitions"><h2>AWARDS &amp; ACHIEVEMENTS｜競賽與榮耀</h2><div className="v3-grid two awards31">{awards.map(a=><article key={a.slug} id={a.slug}><div className="v3-card-image"><Photo name={a.slug}/></div><p className="eyebrow">{a.award}{a.slug==='japan'?' / 2024':''}</p><h3>{a.title}</h3><p className="role">{a.role}</p><p>{a.text}</p><Cta to={'/awards/'+a.slug}>查看更多</Cta></article>)}</div></section>
<section id="capstone"><h2>RESEARCH &amp; PROJECTS｜研究與專案</h2><div className="split31 capstone-patch"><div><h3>AI 時代下人才發展與適應策略</h3><p className="role">文獻整理・研究架構・問題聚焦・概念整合</p><p>以 AI 焦慮、AI 接受、工作生活平衡與工作績效為研究主軸，透過文獻與研究架構梳理人才發展的問題。</p><p>團隊研究涵蓋 347 份有效問卷與 10 位跨產業決策主管及人資專業人士訪談。</p><Cta to="/projects/capstone">查看更多</Cta></div><img src={asset('media/v4/capstone-team.jpg')} alt="輔仁大學企業管理學系畢業專題團隊合影" loading="lazy"/></div><div id="coursework"><div className="v3-grid three">{courses.map(c=><article key={c.slug}><div className="v3-card-image"><Photo name={c.slug}/></div><h3>{c.title.split('｜')[0]}</h3><p className="role">{c.title.split('｜')[1]}</p><p>{c.text}</p><Cta to={'/projects/'+c.slug}>查看更多</Cta></article>)}</div></div></section>
<Academic/><section id="leadership"><h2>EXTRACURRICULAR ACTIVITIES｜課外活動</h2><div className="v3-grid three">{activities.filter(a=>a.slug!=='hrfriday').map(a=><article key={a.slug}><div className="v3-card-image"><Photo name={a.slug}/></div><h3 className={a.slug==='camps2026'?'camp-title':undefined}>{a.title}</h3><p className="role">{a.role}｜{a.date}</p><p>{a.text}</p><Cta to={a.path}>查看更多</Cta></article>)}</div></section>
<section id="honors"><h2>CREDENTIALS｜相關證明</h2><Rail label="榮譽與證照">{published.filter(p=>(p as Slide & {section:string}).section==='honors'||(p as Slide & {section:string}).section.startsWith('certificate-')).filter((p,i,a)=>a.findIndex(x=>x.title===p.title)===i).map(s=><article key={s.id}><img src={asset(s.preview||s.url)} alt={s.title}/><h3>{s.title}</h3><p>{s.issuer}</p><p className="caption">{s.year} · {s.result}</p><a className="cta31" href={asset(s.url)} target="_blank" rel="noopener noreferrer">{s.title}<b aria-hidden="true">↗</b></a></article>)}</Rail></section><Contact/></div>}
const timeline4=[{"date": "2024.07", "title": "宜真佈告欄", "featured": false, "flagship": false}, {"date": "2024.08", "title": "宿舍幹部研習", "featured": false, "flagship": false}, {"date": "2024.08", "title": "宿舍生活宣導影片", "featured": false, "flagship": false}, {"date": "2024.09", "title": "新生入住", "featured": true, "flagship": false}, {"date": "2024.09", "title": "新生說明會暨消防演練", "featured": true, "flagship": false}, {"date": "2024.10", "title": "電影之夜", "featured": false, "flagship": false}, {"date": "2024.10–11", "title": "期中歐趴糖", "featured": false, "flagship": false}, {"date": "2024.11", "title": "宿舍整潔競賽", "featured": false, "flagship": false}, {"date": "2024.12.04", "title": "SuSuSu Super X'mas", "featured": true, "flagship": true}, {"date": "2024.12.18", "title": "冬至湯圓暨期末歐趴糖", "featured": false, "flagship": false}, {"date": "2024.12", "title": "寢室關懷小餅乾", "featured": false, "flagship": false}, {"date": "2025.03.12", "title": "住民大會", "featured": true, "flagship": false}, {"date": "2025.03.12", "title": "國際交換生迎新／交流", "featured": true, "flagship": false}, {"date": "2025.04", "title": "復活節活動", "featured": false, "flagship": false}, {"date": "2025.05", "title": "宜真小活動／粽子大會", "featured": false, "flagship": false}, {"date": "2025.05", "title": "宿舍幹部遴選", "featured": false, "flagship": false}, {"date": "2025.05", "title": "幹部新舊交接", "featured": false, "flagship": false}, {"date": "2025.06", "title": "宿舍年度榮譽大會", "featured": true, "flagship": false}];
function Timeline(){return <section className="timeline4"><p>18 Projects · 500+ Residents · 8 Floor Leaders · One Academic Year</p><ol>{timeline4.map((t,i)=><li key={i} className={t.flagship?'flagship':t.featured?'featured':''}><time>{t.date}</time><span>{t.title}</span>{t.flagship&&<strong>副召集人</strong>}</li>)}</ol></section>}
function StoryDetail(){const loc=useLocation();const story=stories.find(s=>s.path===loc.pathname.replace(/\/$/,''));if(!story)return <NotFound/>;const images=gallery(story.slug);return <div className="wrap article31"><header className="article31-header"><p className="eyebrow">{story.category}</p><h1>{story.title}</h1><p className="role">{story.role}</p><p className="v3-date">{story.date}</p></header><section className="evidence31">{story.slug==='capstone'?<><a className="cta31" href={asset('resources/capstone/v3-report.pdf')} target="_blank" rel="noopener noreferrer">完整文章連結</a><div className="pdf4"><iframe title="畢業專題成果簡報 PDF 預覽" src={asset('media/v4/capstone-presentation.pdf')+'#toolbar=0&navpanes=0'}/></div></>:<Evidence hideCertificates={story.slug==='hrfriday'} slugs={story.resources} images={images.length?images:story.image?gallery('asset-'+story.image):[]}/>}</section>{story.slug!=='capstone'&&<article className="article31-body"><Copy text={story.background}/>{story.slug==='residence'&&<Timeline/>}{story.sections.map((s,i)=><section key={i}>{s.title&&<h2>{s.title}</h2>}<Copy text={s.text}/>{s.items&&<p>{s.items.join("；")}。</p>}</section>)}{story.metrics.length>0&&<aside className="facts31" aria-label="重要數據">{story.metrics.map(m=><p key={m}>{m}</p>)}</aside>}</article>}{story.slug==='hrfriday'&&<section className="certificates4 hr-certificates">{gallery('certificate-hrfriday').map(c=><figure key={c.id}><img src={asset(c.preview||c.url)} alt={c.title} loading="lazy"/><figcaption><strong>{c.title}</strong><p>完成對應課程研習所取得的證明。</p></figcaption></figure>)}</section>}<Back/><Contact/></div>}
function SimpleJob(){const slug=useLocation().pathname.split('/').filter(Boolean).at(-1);const j=jobs.find(j=>j.slug===slug);if(!j)return <NotFound/>;return <div className="wrap article31"><header className="article31-header"><p className="eyebrow">WORK EXPERIENCE</p><h1>{j.company}</h1><p className="role">{j.role}｜{j.date}</p></header>{forProject(j.slug).length>0&&<section className="evidence31"><Evidence slugs={[j.slug]}/></section>}<article className="article31-body"><section><h2>{j.slug==='recruitment'?'人才搜尋與候選人聯繫':'第一線的工作實務'}</h2><p>{j.points.slice(0,2).join('。').replace(/。。/g,'。')}</p></section><section><h2>{j.slug==='recruitment'?'面試協調':'日常營運與服務'}</h2><p>{j.points.slice(2).join('。')}</p></section>{j.slug==='familymart'&&<section><h2>從門市經驗延伸至研究</h2><p>訂購、庫存與顧客服務的觀察，成為理解智慧零售、數據及流程的素材。</p><Cta to="/projects/smart-retail">查看更多</Cta></section>}</article><Back/><Contact/></div>}
function More(){return <div className="wrap article31"><header className="article31-header"><h1>更多課程作品</h1></header>{more.map(([slug,title])=><section id={slug} className="more-detail31" key={slug}><h2>{title}</h2><Evidence slugs={[slug]} images={gallery(slug)}/><div className="article31-body">{slug==='psychology'&&<><h3>專業管理也發生在小型團隊</h3><p>過去我以為只有大公司才需要專業的人力資源管理，也把工商心理學想成揣測人心的工具。課程與期末訪談微電影改變了我的理解：無論組織大小，都會遇到招募、培訓、工作滿意度與團隊合作的問題，而心理學能提供有系統的觀察方法。</p><p>我們訪談一位具社工背景的早餐店老闆娘，觀察她如何理解員工的生活需求、彈性安排工時，並透過日常交流維持團隊關係。這讓我看見理論在小型組織中的應用，也開始把全家門市的工作經驗，連結到 AI、系統工具與人的判斷。</p><h3>我的反思與學習</h3><p>我希望自己在工作與課業上更用心、更專業，也持續理解人工智慧可以如何協助工作。相較於只擔心工作被取代，我更想練習把工具、數據與商業思維連結起來，累積能判斷問題的能力。</p></>}{slug==='labor'&&<><h3>從職位與產出重新理解人資</h3><p>這學期留下最深的印象，是看事情的方式被慢慢調整了。以前容易把能力本身當成價值，課程卻讓我重新問：這個職位為什麼存在、要解決什麼問題、需要產出什麼成果？當職位的目的沒有先釐清，招募、訓練、績效與薪酬也很難有清楚的依據。</p><p>找實習時，我開始更仔細閱讀 JD，也觀察同一家公司正在招募哪些正職職位。我想理解這個工作在組織中的產出是否被重視，以及它對應的發展方向，讓自己能把能力放在合適的位置。</p><h3>公平、制度與表達</h3><p>薪酬管理讓我學習回到標準、依據與制度理解差異，同時思考有限資源下如何管理員工期待。人資需要把員工、主管與公司目標放在一起看，透過人才配置、制度與管理工具，支持組織穩定運作。</p><h3>我的反思與學習</h3><p>我也看見自己在表達上的練習方向：資料很多，不代表觀點清楚。未來除了累積知識，我想更具體地說明完成過什麼、解決了什麼問題，並把複雜內容整理成有依據的核心訊息。</p></>}{slug==='curation'&&<><h3>以策展整理社會議題</h3><p>「酒酒不能自己」是策展概念與實作課程的社會正義組作品。成果簡報保留了團隊對議題的整理與展覽構想，可從作品中查看課程實作的內容。</p></>}{slug==='finance'&&<><h3>台積電赴美設廠的課程探討</h3><p>以台積電赴美設廠為國際財務管理課程主題，成果透過影片呈現。作品保留了課堂對跨國企業議題的整理。</p></>}{slug==='happ'&&<><h3>整合訪談與人資實務</h3><p>擔任書面報告主編，負責簡報與美編。透過真實企業人資訪談，整理職位需求、企業文化、薪酬與留任等議題，將訪談資訊整合為報告。</p></>}{slug==='railway'&&<><h3>從制度改革理解組織</h3><p>擔任組長，負責資訊統籌、重要章節、結論與排版。以台鐵公司化為主題，將制度改革與員工認同、安全、訓練及溝通連結起來。</p></>}</div></section>)}<Back/><Contact/></div>}
function NotFound(){return <section className="wrap not-found"><p>404</p><h1>找不到這個頁面</h1><Back/></section>}
function Effects(){const loc=useLocation();useEffect(()=>{document.title=(stories.find(s=>s.path===loc.pathname.replace(/\/$/,''))?.title||'Anna Peng 彭淑萍')+' | Digital Portfolio';if(!loc.hash){window.scrollTo(0,0);return;}const aliases:Record<string,string>={about:'home',achievements:'competitions',featured:'capstone',education:'academic',certifications:'honors'};const id=loc.hash.slice(1);const timer=setTimeout(()=>document.getElementById(aliases[id]||id)?.scrollIntoView(),100);return()=>clearTimeout(timer);},[loc]);return null}
export default function App(){return <><a className="skip-link" href="#main">跳至主要內容</a><Header/><Effects/><main id="main" tabIndex={-1}><Routes><Route path="/" element={<Home/>}/>{stories.map(s=><Route key={s.path} path={s.path} element={<StoryDetail/>}/>)}{['recruitment','familymart','caves'].map(slug=><Route key={slug} path={'/experience/'+slug} element={<SimpleJob/>}/>)}<Route path="/learning/more" element={<More/>}/><Route path="*" element={<NotFound/>}/></Routes></main><footer className="wrap v3-footer">© 2026 Anna Peng. All Rights Reserved. Built with Codex.</footer></>}
