import {Link} from 'react-router-dom';
import {asset,forProject} from './content/resources';
import './v2.css';
const links=(slug:string)=>forProject(slug).map(r=><a key={r.id} href={r.external?r.url:asset(r.url)} target="_blank" rel="noopener noreferrer">{r.label} ↗</a>);
const photo=(name:string,alt:string)=><img src={asset('images/'+name+'.webp')} alt={alt} loading="lazy"/>;
const featured=[
 {slug:'hrfriday',title:'HRFriday｜第六屆高潛學員招募專案',intro:'招募專案副召集人',points:['參與招募規劃、時程分工、履歷篩選、面試安排與跨組執行','團隊成果：41 份申請 → 20 位面試 → 12 位錄取','從候選人角色走向招募流程的規劃與執行']},
 {slug:'sel',title:'偏鄉中心｜SEL 教材與培訓設計',intro:'教育訓練、學習內容設計與培訓執行',image:'v2-sel',points:['主導兩學期 SEL 教材與簡報製作','累積 4 支培訓影片','接洽並執行 1 場 SEL 月培訓講座']},
 {slug:'capstone',title:'畢業專題｜AI 時代下人才發展與適應策略',intro:'2025.02－2025.12',image:'v2-capstone',points:['聚焦 AI 焦慮、接受度、工作生活平衡與績效','參與文獻整理、研究架構、問題聚焦與概念整合','連結人才發展、員工適應與 AI × 人資議題']},
 {slug:'smart-retail',title:'產業管理研討｜智慧零售研究',intro:'從便利商店第一線經驗延伸至產業研究',image:'v2-retail',points:['主要負責定義、便利商店供應鏈、智慧零售趨勢、市場資料與結論','學習定義研究邊界、整理資料並轉化成可支持結論的資訊']}
];
export default function HomeV2(){return <div className="v2 wrap">
 <section id="home" className="v2-intro"><div id="about"><p className="v2-kicker">關於我</p><h1>彭淑萍 <span>Anna Peng</span></h1><p className="v2-school">輔仁大學企業管理學系<br/>輔修財經法律｜企業財稅學分學程<br/>預計 2026 年 12 月畢業</p><p>主修企業管理，並透過財經法律與企業財稅拓展理解企業的角度。</p><p>從門市服務、偏鄉教育、招募實作到活動統籌與跨域研究，持續累積理解需求、整合資訊與推進執行的能力。</p><p>目前關注招募、人才發展、研究分析與專案協調，也持續探索人資數位化、AI 協作流程與 People Operations。</p><div className="v2-tags">{['HRFriday 人資小週末第五屆高潛學員','招募實務','教育訓練','專案協調','研究分析'].map(t=><span key={t}>{t}</span>)}</div><p className="v2-motto">找到自己真正喜歡的事，並讓喜歡的事變得有價值。</p></div><img className="v2-portrait" src={asset('images/anna-hero.webp')} alt="彭淑萍 Anna Peng" fetchPriority="high"/></section>
 <section id="experience"><h2>工作與實習</h2><div className="v2-job"><div><h3>和運租車｜管理部實習生</h3><small>2026－目前</small></div><p>現於管理部實習，目前仍在整理可公開的完整實習成果。</p></div><div className="v2-job"><div><h3>輔仁大學台灣偏鄉教育關懷中心｜約聘助理</h3>{photo('community','偏鄉中心帶班團隊與主任合照')}</div><div><ul><li>執行校園招募與學伴營運，單學期招募逾 100 名大學生，約完成 70% 學伴人力需求</li><li>支援每梯次約 60 組大小學伴的出缺席、補位與師長聯繫</li><li>參與教育訓練、SEL 教材與培訓內容製作，累積招募、培訓、內容設計與專案營運經驗</li></ul><Link to="/experience/community">工作詳情 →</Link></div></div><div className="v2-job"><div><h3>亞瑞特數位社群行銷有限公司｜招募工讀生</h3><small>2025.07－2025.08</small></div><p>每日搜尋與篩選約 30–50 份履歷；執行電話聯繫與面試安排，協助補實 1 項職缺。</p></div><div className="v2-job"><div><h3>全家便利商店｜高階服務人員</h3><small>2023.04－目前（以來源當時狀態）</small></div><p>商品訂貨、驗收、陳列、效期與庫存管理；顧客服務與每日營收核對；經營約 200 人團購社群。</p></div><p className="v2-other">其他經歷：敦煌書局校園店｜2023.02－2025.09　／　黃漢邦數學教室｜電話聯繫｜2019.06－2020.09</p></section>
 <section id="featured"><h2>精選專案</h2><div className="v2-projects">{featured.map(p=><article key={p.slug}>{p.image?photo(p.image,p.title):<div className="v2-numbers">41 → 20 → 12<small>團隊招募成果：申請／面試／錄取</small></div>}<h3>{p.title}</h3><p className="v2-kicker">{p.intro}</p><ul>{p.points.map(t=><li key={t}>{t}</li>)}</ul><Link to={'/projects/'+p.slug}>專案詳情與成果 →</Link></article>)}</div></section>
 <section id="competitions"><span id="achievements"/><h2>競賽成果</h2><div className="v2-two"><article id="future2035" className="v2-media">{photo('competition','2035 青年人生活情境競賽')}<div><strong>銀質獎／第二名</strong><h3>2035 青年人生活情境競賽｜聽見「心」未來</h3><p>組長、主題發想、競賽窗口、分工協調、主要發表者。與心理與企管背景成員跨域合作，從員工狀態、EAP、個資與風險思考方案，重視可行性與風險意識。</p><div className="v2-links">{links('future2035')}</div></div></article><article id="japan" className="v2-media">{photo('japan','2024 跨域學習成果競賽成果照片')}<div><strong>第一名</strong><h3>2024 跨域學習成果競賽</h3><p>擔任組長，進行日本旅遊／住宿資料蒐集、清理與整理，使用 Gemini Data 進行操作與解讀，完成成果整合與發表。</p><div className="v2-links">{links('japan')}</div></div></article></div></section>
 <section id="leadership"><h2>領導與服務</h2><div className="v2-three"><article>{photo('v2-leadership','苑代表於榮譽大會上台會報')}<h3>宜真宜善學苑｜苑代表</h3><small>2024.07－2025.06</small><p>服務 500+ 位住民，協調 8 位樓層幹部，統籌一學年 18 項活動與營運工作。負責活動規劃、預算、住民溝通與團隊協調。</p><Link to="/leadership/residence">年度活動與領導專案 →</Link></article><article>{photo('v2-camp2026','伴您好讀國小組')}<h3>2026《伴您好讀》聯合相見歡</h3><small>國小組活動組總負責人</small><p>約 35 位國小學童、四天三夜。負責活動企劃、時間、餐食、主持、協調與現場處理。</p><div className="v2-links">{links('camps2026')}</div></article><article>{photo('v2-camp2024','莿桐夏日學堂書屋合照')}<h3>2024 台東莿桐夏日學堂</h3><small>隊長</small><p>一週課程設計、活動細流與團隊協調。受颱風影響時重新調整原規劃內容，累積臨場應變與團隊合作經驗。</p></article></div></section>
 <section id="learning"><h2>專業學習</h2><div className="v2-three v2-learning"><article><h3>HRFriday 人資小週末</h3><small>第五屆高潛學員</small><p>招募甄選與 JD、訓練發展、薪酬福利、員工關係、勞動法規、PIP、OGSM、IDP、AI 與人資議題。</p></article><article><h3>科技人資先修班</h3><small>持續探索人資數位化與 AI 協作</small><p>關注人資與 AI 數位平台、人資數據庫、人資 AI Agent、AI 時代的人才與組織轉型、多模態 AI 與人才管理。</p></article><article><h3>大學代表課程</h3><ul className="v2-course"><li><Link to="/projects/terra">人力資源管理｜Terra 模擬企業</Link></li><li>人力規劃與選才｜Happ. 小樹屋</li><li><Link to="/projects/smart-retail">產業管理研討｜智慧零售</Link></li><li><Link to="/projects/bamboo-tea">組織學習與社會探究｜竹峰茗茶</Link></li><li>組織與社會發展｜台鐵公司化</li><li>勞資關係與薪酬管理</li></ul><Link to="/learning/more">更多課程作品 →</Link></article></div></section>
 <section id="education"><h2>教育與資格</h2><div className="v2-two"><p><strong>輔仁大學｜企業管理學系</strong><br/>輔修財經法律｜修習企業財稅學分學程<br/>預計 2026 年 12 月畢業</p><div id="certifications" className="v2-tags"><span>TOEIC｜740</span><span>全民英檢｜中級</span><span>Google Analytics｜認證</span></div></div></section>
 <section id="contact"><h2>聯絡方式</h2><div className="v2-links"><a href="mailto:aa411382423@gmail.com">Email：aa411382423@gmail.com</a><a href="https://www.linkedin.com/in/annalearner/">LinkedIn ↗</a><a href="https://github.com/aa2423-bit">GitHub ↗</a></div></section>
 </div>}
